// Original clues inspired by the synonym-and-circumlocution mechanic of Idiom Addict.
// Each clue avoids answer content words and stays grammatical when read aloud.
const synonymTwists = [
  ["A snack-sized splinter perched beside your neck", "A chip on your shoulder", "M"],
  ["The instant someone releases their head covering", "At the drop of a hat", "M"],
  ["Every passenger sharing one floating conveyance", "All in the same boat", "M"],
  ["One reaching appendage plus one walking appendage", "An arm and a leg", "E"],
  ["Yapping toward a completely unrelated piece of lumber", "Barking up the wrong tree", "M"],
  ["Striking everything surrounding the shrubbery", "Beat around the bush", "M"],
  ["The finest development following pre-portioned toast material", "Best thing since sliced bread", "H"],
  ["Sink your teeth into the ammunition", "Bite the bullet", "M"],
  ["Fracture one of your walking supports", "Break a leg", "E"],
  ["Set fire to the fuel reserved for twelve at night", "Burn the midnight oil", "H"],
  ["Escaping by the outermost coating of your chewing equipment", "By the skin of your teeth", "H"],
  ["Declare the remaining hours officially finished", "Call it a day", "M"],
  ["Discovered with freshly crimson gripping tools", "Caught red-handed", "M"],
  ["Priced at one reaching limb and one walking limb", "Cost an arm and a leg", "M"],
  ["Slice straight to the pursuit", "Cut to the chase", "M"],
  ["One small silver coin buys twelve of them", "Dime a dozen", "H"],
  ["Waste no tears on dairy already covering the floor", "Don't cry over spilled milk", "H"],
  ["Approaching the final strand of metal", "Down to the wire", "M"],
  ["Sketch the boundary nobody may cross", "Draw the line", "M"],
  ["Tumbling at the survival rate of winged pests", "Dropping like flies", "M"],
  ["Effortlessly performs the deed", "Easy does it", "H"],
  ["Every gloomy mass of vapor hides a precious-metal border", "Every cloud has a silver lining", "H"],
  ["Turn toward the melody and accept the consequences", "Face the music", "M"],
  ["As healthy as a small bowed instrument", "Fit as a fiddle", "M"],
  ["Escape from the grasp", "Get out of hand", "H"],
  ["Gather your entire performance into one place", "Get your act together", "M"],
  ["Award uncertainty the favorable assumption", "Give the benefit of the doubt", "H"],
  ["Return to the first box on the board", "Go back to square one", "M"],
  ["Travel beyond the required distance", "Go the extra mile", "M"],
  ["Remain suspended at your present location", "Hang in there", "H"],
  ["Strike the fastener precisely on its crown", "Hit the nail on the head", "M"],
  ["Punch the cloth container used at bedtime", "Hit the sack", "M"],
  ["Submerged in liquid that is uncomfortably warm", "In hot water", "M"],
  ["This dance requires exactly a pair", "It takes two to tango", "H"],
  ["Leap aboard the vehicle carrying the musicians", "Jump on the bandwagon", "M"],
  ["Maintain your jaw in an elevated position", "Keep your chin up", "M"],
  ["Deliver a boot to the handled container", "Kick the bucket", "M"],
  ["Release the whiskered animal from its cloth container", "Let the cat out of the bag", "M"],
  ["Arrive too late to board the departing vessel", "Miss the boat", "M"],
  ["Absent agony, absent advancement", "No pain, no gain", "M"],
  ["Positioned directly atop the sporting sphere", "On the ball", "H"],
  ["Standing above dangerously fragile frozen water", "On thin ice", "M"],
  ["A single occurrence beneath a strangely colored lunar body", "Once in a blue moon", "H"],
  ["Arriving unexpectedly from the sky’s color", "Out of the blue", "H"],
  ["One serving of frosted baked dessert", "Piece of cake", "M"],
  ["Drag your scattered self back into one unit", "Pull yourself together", "H"],
  ["Cause precipitation over someone’s festive procession", "Rain on your parade", "M"],
  ["Interpret what was never printed in the spaces between rows", "Read between the lines", "H"],
  ["Mention the evil one and watch who appears", "Speak of the devil", "M"],
  ["Scatter the legumes and expose the secret", "Spill the beans", "M"],
  ["Swallow that claim with one tiny crystal of seasoning", "Take it with a grain of salt", "H"],
  ["The sporting sphere now occupies your side of the playing area", "The ball is in your court", "M"],
  ["The finest parts of two separate realities", "The best of both worlds", "H"],
  ["Toss your drying cloth into the contest", "Throw in the towel", "M"],
  ["The clock grows wings whenever you are enjoying yourself", "Time flies when you're having fun", "M"],
  ["Only the peak of the floating frozen mountain is visible", "Tip of the iceberg", "M"],
  ["Feeling poorly beneath the atmospheric conditions", "Under the weather", "H"],
  ["Suspended overhead with no decision attached", "Up in the air", "H"],
  ["Encircle a difficult idea using your skull", "Wrap your head around it", "H"],
  ["Your estimate is no worse than the one I could offer", "Your guess is as good as mine", "H"],
  ["A fortunate event wearing an unrecognizable costume", "A blessing in disguise", "H"],
  ["One copper coin in exchange for whatever occupies your mind", "A penny for your thoughts", "H"],
  ["A single image carries the value of ten hundred terms", "A picture is worth a thousand words", "H"],
  ["Pour more combustible material onto the flames", "Add fuel to the fire", "M"],
  ["Return to the plank where plans are illustrated", "Back to the drawing board", "H"],
  ["Fold your body in the least convenient direction", "Bend over backwards", "M"],
  ["Remove a mouthful larger than your jaw can process", "Bite off more than you can chew", "M"],
  ["Discharge your excess heated vapor", "Blow off steam", "M"],
  ["Fracture the frozen surface between strangers", "Break the ice", "M"],
  ["Rupture the delicate sphere around someone’s optimism", "Burst your bubble", "H"],
  ["Wait to traverse that crossing until you actually reach it", "Cross that bridge when we come to it", "H"],
  ["Excessive inquisitiveness proved fatal to the household feline", "Curiosity killed the cat", "M"],
  ["Receive a sample of the treatment you normally prescribe", "Get a taste of your own medicine", "H"],
  ["Venture onto the unsupported end of a tree branch", "Go out on a limb", "M"],
  ["Make contact with the earth while already sprinting", "Hit the ground running", "M"],
  ["Inside the very last notch available on the clock", "In the nick of time", "H"],
  ["Reduce an extended tale to its briefest form", "Make a long story short", "M"],
  ["Tug another person’s walking appendage", "Pull someone's leg", "M"],
  ["Place every future bird inside a single woven container", "Put all your eggs in one basket", "H"],
  ["Take credit for someone else’s loud weather event", "Steal someone's thunder", "H"],
  ["The enormous gray mammal everyone is ignoring indoors", "The elephant in the room", "M"],
  ["Remaining loyal through both dense and narrow conditions", "Through thick and thin", "H"],
  ["Yesterday’s liquid has already passed beneath the crossing", "Water under the bridge", "H"]
];

const mixedMessages = [
["Treating a minor issue as though it were a major disaster","Make a mountain out of a molehill","M"],
["From torn-up cloth remnants all the way to great wealth","From rags to riches","M"],
["The reminder to understand another person’s experience before criticizing","Walk a mile in someone's shoes","M"],
["Why one certain opportunity beats several possibilities you cannot secure","A bird in the hand is worth two in the bush","H"],
["When everyone recognizes the major problem but nobody will mention it","The elephant in the room","M"],
["A plan to delay solving a possible problem until it actually occurs","Cross that bridge when we come to it","H"],
["How to describe two people who cannot agree on an issue","They don't see eye to eye","M"],
["Doing an unpleasant or frightening task instead of avoiding it","Bite the bullet","M"],
["A request to skip the unnecessary details and reach the important part","Cut to the chase","M"],
["The first friendly move that makes an awkward group comfortable","Break the ice","H"],
["When a person suffers the same unpleasant treatment they gave everyone else","Get a taste of your own medicine","H"],
["Avoiding the real point by discussing every nearby subject instead","Beat around the bush","H"],
["The hopeful idea that one lost opportunity creates room for another","When one door closes, another opens","M"],
["Why someone else’s situation often looks better from a distance","The grass is always greener on the other side","H"],
["Concealed in a location so obvious that nobody thinks to search there","Hiding in plain sight","M"],
["The claim that behavior provides stronger proof than promises do","Actions speak louder than words","M"],
["A warning that appearance alone cannot reveal content or quality","Don't judge a book by its cover","M"],
["Enjoying the advantages of two normally separate choices at once","The best of both worlds","H"],
["Arriving at the final possible moment before failure","In the nick of time","H"],
["The rule that meaningful improvement usually requires discomfort","No pain, no gain","M"]
];

const cards = [
  ...synonymTwists.map(card => [...card, "SYNONYM TWIST"]),
  ...mixedMessages.map(card => [...card, "MIXED MESSAGE"])
];
